name: Generate Tetris Graph

# when to run the workflow
on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:          # you can run manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Tetris Graph
        uses: zluvsand/github-tetris-graph@main
        with:
          file: pacman-contribution-graph.svg

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Tetris graph"
          file_pattern: pacman-contribution-graph.svg
